<a href="https://colab.research.google.com/github/imrahul361/Colab-with-TensorFlow-2.0-Beta/blob/master/NPTEL_Week2_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from sklearn import metrics
C="A"
F="B"
H="C"

# True values
y_true = [C,C,F,F,F,F,F,H,H,H]
# Predicted values
y_pred = [C,F,F,F,H,H,H,H,H,H]

# Print the confusion matrix
print(metrics.confusion_matrix(y_true, y_pred))

# Print the precision and recall, among other metrics
print(metrics.classification_report(y_true, y_pred, digits=3))


[[1 1 0]
 [0 2 3]
 [0 0 3]]
              precision    recall  f1-score   support

           A      1.000     0.500     0.667         2
           B      0.667     0.400     0.500         5
           C      0.500     1.000     0.667         3

    accuracy                          0.600        10
   macro avg      0.722     0.633     0.611        10
weighted avg      0.683     0.600     0.583        10



In [1]:
import numpy as np
r =  np.random.rand()
beta = 1 - 10**(-r+1)
print(beta)

-4.631828490152401
